on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install --force
    #    npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.showcaseurbusiness.com
        username: ftpgitshowcase@app.showcaseurbusiness.com
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        server-dir: /app.showcaseurbusiness.com/ftpgitshowcase/
